window.HFAH_LEARNING = {
  disclaimer:
    "This is not financial advice. Hedge Fund at Home is educational software. " +
    "Use simulated mode for learning. Do not use real money to complete this curriculum. " +
    "Past simulated results do not predict future performance.",
  pipeline: [
    { label: "Data", detail: "Daily bars from market data (yfinance in the kit)" },
    { label: "Signal", detail: "Your Strategy.on_bars() proposes orders" },
    { label: "Risk", detail: "RiskGate checks limits and kill switch" },
    { label: "Execution", detail: "Simulated broker by default (optional IBKR paper)" },
  ],
  stages: [
    {
      id: "stage-1",
      title: "Read safety and scope",
      optional: false,
      body: "Understand why simulated mode is default and why this is not investment advice.",
      tasks: [
        { text: "Read DISCLAIMER.md", doc: "DISCLAIMER.md" },
        { text: "Read EDUCATION.md", doc: "docs/EDUCATION.md" },
        { text: "Read README execution modes", doc: "README.md" },
      ],
      checkpoint: "You can explain simulated mode and that this is not financial advice.",
      commands: [],
    },
    {
      id: "stage-2",
      title: "Run without a broker",
      optional: false,
      body: "Install the kit and run one simulated cycle. No brokerage connection.",
      tasks: [
        { text: "Create venv and install package" },
        { text: "Copy config from example" },
        { text: "Run once and find simulated_fill in logs" },
      ],
      checkpoint: "You see simulated_fill and know no brokerage was contacted.",
      commands: [
        "cd hedge-fund-at-home",
        "python -m venv .venv && source .venv/bin/activate",
        'pip install -e ".[dev]"',
        "cp .env.example .env",
        "cp config/config.yaml.example config/config.yaml",
        "python -m hedgekit.cli.run --once",
      ],
    },
    {
      id: "stage-3",
      title: "Trace the code path",
      optional: false,
      body: "Read the four files that implement the loop end to end.",
      tasks: [
        { text: "hedgekit/execution/runner.py", doc: "hedgekit/execution/runner.py" },
        { text: "hedgekit/strategy/base.py", doc: "hedgekit/strategy/base.py" },
        { text: "hedgekit/risk/gate.py", doc: "hedgekit/risk/gate.py" },
        { text: "hedgekit/broker/simulated.py", doc: "hedgekit/broker/simulated.py" },
      ],
      checkpoint: "You can sketch: bars → strategy → risk → broker.",
      commands: [],
    },
    {
      id: "stage-4",
      title: "Simulated historical walk",
      optional: false,
      body: "Walk history with the simulated broker only. This is a teaching harness.",
      tasks: [{ text: "Run backtest and note fills vs risk rejects" }],
      checkpoint: "You know this is not a forecast of returns.",
      commands: [
        "python -m hedgekit.cli.backtest --start 2023-01-01 --end 2024-12-31",
      ],
    },
    {
      id: "stage-5",
      title: "Study the example strategy",
      optional: false,
      body: "Open the mean reversion example and change entry_z in config.",
      tasks: [
        { text: "Read strategies/example_mean_reversion/strategy.py" },
        { text: "Edit entry_z in config/config.yaml" },
        { text: "Re-run backtest and compare trade count" },
      ],
      checkpoint: "You predicted trade count direction before re-running.",
      commands: ["python -m hedgekit.cli.backtest"],
    },
    {
      id: "stage-6",
      title: "Build a toy strategy",
      optional: false,
      body: "Copy the example folder and register your own module in config.",
      tasks: [
        { text: "Copy example_mean_reversion to a new folder" },
        { text: "Implement a trivial on_bars() rule" },
        { text: "Run pytest -q" },
      ],
      checkpoint: "Your strategy loads and tests pass.",
      commands: ["pytest -q"],
    },
    {
      id: "stage-7",
      title: "Optional paper trading lab",
      optional: true,
      body: "Only after stages 1-6. IBKR paper port only. ENABLE_LIVE_TRADING stays false.",
      tasks: [
        { text: "Read docs/IBKR_SETUP.md", doc: "docs/IBKR_SETUP.md" },
        { text: "Start TWS or Gateway paper" },
        { text: "Set mode paper and IBKR_USE_REAL=true" },
      ],
      checkpoint: "You can name three differences: simulated vs paper fills.",
      commands: [],
    },
    {
      id: "stage-8",
      title: "Live trading (not in curriculum)",
      optional: true,
      locked: true,
      body: "Not part of learning. Real capital can be lost. Consult professionals if you ever consider it.",
      tasks: [],
      checkpoint: "You understand why this stage is excluded from the path.",
      commands: [],
    },
  ],
  topics: [
    {
      id: "markets",
      title: "Markets and data",
      bullets: [
        "OHLCV bars and corporate actions",
        "Adjusted vs unadjusted prices",
        "Survivorship bias in free databases",
        "Market hours and liquidity",
      ],
      research: [
        "survivorship bias backtest",
        "corporate actions adjustment",
        "yfinance data limitations",
      ],
    },
    {
      id: "signals",
      title: "Signals and statistics",
      bullets: [
        "Mean reversion vs momentum",
        "Z-scores and overfitting",
        "Correlation vs cointegration (intro)",
        "Stationarity basics",
      ],
      research: [
        "Engle-Granger cointegration intuitive",
        "overfitting quantitative trading",
        "multiple testing bias finance",
      ],
    },
    {
      id: "backtest",
      title: "Backtesting honesty",
      bullets: [
        "In-sample vs out-of-sample",
        "Look-ahead bias",
        "Costs and slippage in simulation",
        "Why historical Sharpe often shrinks",
      ],
      research: [
        "backtest overfitting Bailey Lopez de Prado",
        "deflated Sharpe ratio",
      ],
    },
    {
      id: "risk",
      title: "Risk management",
      bullets: [
        "Per-symbol and gross exposure limits",
        "Daily loss and kill switch",
        "Concentration risk",
        "Simulated vs paper vs live fills",
      ],
      research: [
        "risk of ruin trading",
        "Kelly criterion caution retail",
        "maximum drawdown interpretation",
      ],
    },
    {
      id: "execution",
      title: "Execution and brokers",
      bullets: [
        "Market vs limit orders",
        "Paper vs simulated fills",
        "IBKR API basics",
        "Partial fills and friction",
      ],
      research: ["IBKR paper trading documentation", "market impact retail size"],
    },
    {
      id: "engineering",
      title: "Software engineering",
      bullets: [
        "Idempotent orders and logging",
        "Config vs secrets (.env, AWS)",
        "Tests before live data",
        "Why one process is easier to learn first",
      ],
      research: ["idempotency trading systems", "twelve-factor app config"],
    },
  ],
  journalPrompts: [
    "What does my strategy do on a flat market? On a crash window?",
    "How many parameters did I tune by hand? Could I be overfitting?",
    "What happens if I double position size in config?",
    "What is different between simulated and paper fills?",
    "Where does the kill switch reject orders in code?",
  ],
};
